{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rate-limiter.serviceAccountName" . }}
  labels:
    {{- include "rate-limiter.labels" . | nindent 4 }}
{{- end }}
